# Generated by Django 4.2.3 on 2023-07-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table='purchase',
        ),
    ]
