# Generated by Django 4.2.3 on 2023-07-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_purchase_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('-purchase_date',)},
        ),
    ]
